
import { Vector3 } from 'three';

// Data extracted from audio analysis, now simplified to just duration.
export interface AudioFeatures {
  duration: number;
  // Loudness, spectral centroid, and peaks are now analyzed by Gemini.
}

// An individual segment of the rollercoaster track as defined by the AI
export interface TrackSegment {
  component: 'climb' | 'drop' | 'turn' | 'loop' | 'barrelRoll';
  angle?: number;
  length?: number;
  direction?: 'left' | 'right';
  radius?: number;
  rotations?: number;
}

// The full blueprint for the ride, generated by Gemini
export interface RideBlueprint {
  palette: string[];
  track: TrackSegment[];
}

// Represents the application's current state in its lifecycle
export enum AppStatus {
  Idle = 'IDLE',
  Analyzing = 'ANALYZING',
  Generating = 'GENERATING',
  Ready = 'READY',
  Riding = 'RIDING',
  Error = 'ERROR',
}

// Processed data ready for building the 3D track in Three.js
export interface TrackData {
    path: Vector3[];
    upVectors: Vector3[]; // Crucial for handling barrel rolls correctly
    railColor: string;
    glowColor: string;
    skyColor1: string;
    skyColor2: string;
}