# This file is auto-generated by scripts/sync-constants.mjs. Do not edit manually.

TRACK_STYLES = [
  "classic",
  "extreme",
  "flowing",
  "technical",
  "experimental"
]

WORLD_THEMES = [
  "fantasy",
  "cyberpunk",
  "aurora",
  "desert",
  "space",
  "underwater",
  "noir"
]

VISUAL_STYLES = [
  "photorealistic",
  "stylized",
  "painterly",
  "lowpoly",
  "retro"
]

DETAIL_LEVELS = [
  "low",
  "medium",
  "high"
]

CAMERA_PRESETS = [
  "epic",
  "immersive",
  "first_person",
  "wide_angle"
]

EVENT_PRESETS = [
  "fog",
  "fireworks",
  "starshow",
  "lightBurst",
  "sparkRing",
  "confetti"
]

RIDE_CONFIG = {
  "CAMERA_BASE_FOV": 75,
  "CAMERA_MAX_FOV_BOOST": 25,
  "CAMERA_SPEED_FOV_FACTOR": 5,
  "INITIAL_TRACK_SEGMENT_LENGTH": 50,
  "INITIAL_TRACK_SEGMENT_SPACING": 2.5,
  "TRACK_SEGMENT_RESOLUTION": 100,
  "PARTICLE_COUNT": 10000,
  "PARTICLE_SPAWN_COUNT": 200,
  "PARTICLE_BASE_SIZE": 0.5,
  "CAMERA_NEAR": 0.1,
  "CAMERA_FAR": 2000,
  "FOG_NEAR": 100,
  "FOG_FAR": 1000,
  "AMBIENT_LIGHT_INTENSITY": 0.4,
  "DIRECTIONAL_LIGHT_INTENSITY": 0.8,
  "BACKLIGHT_INTENSITY": 0.3,
  "MAX_DPR": 2,
  "FPS_METER_INTERVAL": 1000,
  "GHOST_RIBBON_RADIUS": 2,
  "BASS_GLOW_MIN": 0.1,
  "BASS_GLOW_MAX": 1.5,
  "LERP_FACTOR": 0.15,
  "TRACK_DEFAULT_OPACITY": 0.9,
  "TRACK_INSIDE_OPACITY": 0.7,
  "TRACK_OPACITY_LERP_SPEED": 2,
  "PLACE_TRACK_UNDER_CAMERA": False,
  "TRACK_UNDER_CAMERA_VERTICAL_OFFSET": -5,
  "TRACK_RADIUS": 0.5,
  "PERFORMANCE_CHECK_INTERVAL": 5000,
  "TARGET_FPS": 60,
  "LOW_QUALITY_DEBOUNCE_MS": 3000
}

DEFAULT_SPACING = 2.5

SCENE_CONFIG = {
  "DEFAULT_BACKGROUND_TOP_COLOR": "#0a0a1a",
  "DEFAULT_BACKGROUND_BOTTOM_COLOR": "#000000",
  "DEFAULT_FOG_COLOR": "#000000"
}

